server:
  port: 8088
  servlet:
    context-path: /shopping-mall
spring:
  jpa:
    database: mysql
    show-sql: off  #展示sql语句
    open-in-view: off   # 去除警告
    generate-ddl: true  # 是否生成ddl语句
    properties:
      hibernate:
        format_sql: true  #格式化sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swagger报错的问题
    #用于访问静态文件，省略路径和后缀名
    view:
      prefix: /
      suffix: .html
  redis:
    database: 0
    host: ###{redisHost}
    port: ###{redisPort}
    password: ###{redisPassword}
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
zyh-datasource:
  data-source-type: hikari
  switch-slave-type: random
  hikari:
    master:
      jdbc-url: jdbc:mysql://###{sqlHost}:###{sqlPort}/shopping-mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: ###{sqlUser}
      password: ###{sqlPassword}
    slaves:
      - jdbc-url: jdbc:mysql://###{sqlHost}:###{sqlPort}/shopping-mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: ###{sqlUser}
        password: ###{sqlPassword}
## 关于自己的配置
self:
  config:
    # 商店名字
    store-name: ###{storeName}
    # 邮箱配置
    email:
      from-email: ###{emailUser}
      host: ###{emailHost}
      port: ###{emailPort}
      email-password: ###{emailPassword}
    #加密的盐
    password:
      salt: ###{passwordSalt}
    #wechat
    wechat:
      app-id: ###{wechatAppId}
      app-secret: ###{wechatAppSecret}
      #回调地址，写本地地址就行，但是不要写127和localhost
      redirect_url: ###{wechatRedirectUrl}
    head-img-file:
      # 头像图片不得超过的大小（大约1mb）
      imgSize: 1048576
    pay:
      # 前端主页(取消支付回调地址)
      request-from-url: http://localhost/shopping-mall